### ISSUE TITLE
How to open the ios  wireless ？

### ISSUE THREAD

**Issue by Haif-07** [IGPenguin/mobile-toolkit#224]

**Comment by IGPenguin** [comment]
Hello @Haif-07, there's currently no way to handle this via Mobile Toolkit.

You can use the scripts wirelessly, but you need to enable the wireless access in Xcode.
Please refer to the official Apple documentation: 
https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/devbc48d1bad
