### ISSUE TITLE
arecord not working properly after the last update

### ISSUE THREAD

**Issue by vrbajiva** [IGPenguin/mobile-toolkit#227]
### 🐞 What's wrong
`arecord` not working after the last update - it looks like the recording is immediately automatically ended and no file is saved

<img width="443" alt="lenkavrbova@Lenka-MacBook-Air:~:Desktop 23-08-28 13-01-05" src="https://github.com/IGPenguin/mobile-toolkit/assets/45257246/39517d21-1133-428c-b97b-a22a8d644daf">

### 🌈 Desired state
`arecord -l` is working fine, it would be nice to be able to use only `arecord` without the `-l` flag

**Comment by IGPenguin** [comment]
Hey @vrbajiva, can you please provide the details (OS version, model, manufacturer...) about the device you are experiencing issues on?

The `-l` flag stands for `legacy`, it's available specifically for cases when you are recording screen on older devices, that might experience issues with [scrcpy](https://github.com/Genymobile/scrcpy).

I'd prefer keeping the current setup - [scrcpy](https://github.com/Genymobile/scrcpy) being default capture method, if the issues are experienced only on a small fraction of Android devices.

Thanks! 🙌

**Comment by vrbajiva** [comment]
Resolved by updating scrcpy by `brew install scrcpy` 🚀 Thanks @IGPenguin 💙
